edition = "2021"
tab_spaces = 4
format_code_in_doc_comments = true
wrap_comments = false
format_strings = false
hard_tabs = false
reorder_imports = true
imports_granularity = "Item"
group_imports = "StdExternalCrate"
where_single_line = true
trailing_comma = "Vertical"
overflow_delimited_expr = true
